2016-08-17 01:12:58.785 [debug] <0.54.0>@lager_handler_watcher:94 Lager installed handler {lager_file_backend,
                            "/root/bin/basho_bench/tests/20160817_011258/error.log"} into lager_event
2016-08-17 01:12:58.785 [debug] <0.56.0>@lager_handler_watcher:94 Lager installed handler {lager_file_backend,
                            "/root/bin/basho_bench/tests/20160817_011258/console.log"} into lager_event
2016-08-17 01:12:58.785 [debug] <0.58.0>@lager_handler_watcher:94 Lager installed handler error_logger_lager_h into error_logger
2016-08-17 01:12:58.815 [debug] <0.41.0> Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.60.0>
2016-08-17 01:12:58.815 [debug] <0.40.0> Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.61.0>
2016-08-17 01:12:58.815 [debug] <0.42.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.62.0>
2016-08-17 01:12:58.816 [debug] <0.42.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0}]) at pid <0.63.0>
2016-08-17 01:12:59.265 [debug] <0.50.0>@lager_handler_watcher:94 Lager installed handler lager_backend_throttle into lager_event
2016-08-17 01:12:59.318 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-17 01:12:59.319 [notice] <0.47.0>@lager_file_backend:127 Changed loglevel of /root/bin/basho_bench/tests/20160817_011258/console.log to debug
2016-08-17 01:12:59.329 [info] <0.2.0>@basho_bench:log_dimensions:253 Est. data size: 953.67 MB
2016-08-17 01:12:59.384 [debug] <0.72.0> Supervisor sasl_safe_sup started alarm_handler:start_link() at pid <0.73.0>
2016-08-17 01:12:59.384 [debug] <0.72.0> Supervisor sasl_safe_sup started overload:start_link() at pid <0.74.0>
2016-08-17 01:12:59.385 [debug] <0.71.0> Supervisor sasl_sup started supervisor:start_link({local,sasl_safe_sup}, sasl, safe) at pid <0.72.0>
2016-08-17 01:12:59.396 [debug] <0.71.0> Supervisor sasl_sup started release_handler:start_link() at pid <0.75.0>
2016-08-17 01:12:59.396 [info] <0.7.0> Application sasl started on node nonode@nohost
2016-08-17 01:12:59.451 [debug] <0.80.0> Supervisor crypto_sup started crypto_server:start_link() at pid <0.81.0>
2016-08-17 01:12:59.451 [info] <0.7.0> Application crypto started on node nonode@nohost
2016-08-17 01:12:59.476 [debug] <0.90.0> Supervisor folsom_sup started folsom_sample_slide_sup:start_link() at pid <0.91.0>
2016-08-17 01:12:59.481 [debug] <0.90.0> Supervisor folsom_sup started folsom_meter_timer_server:start_link() at pid <0.92.0>
2016-08-17 01:12:59.485 [debug] <0.90.0> Supervisor folsom_sup started folsom_metrics_histogram_ets:start_link() at pid <0.93.0>
2016-08-17 01:12:59.485 [info] <0.7.0> Application folsom started on node nonode@nohost
2016-08-17 01:12:59.521 [info] <0.86.0>@basho_bench_stats_writer_csv:new:43 module=basho_bench_stats_writer_csv event=start stats_sink=csv
2016-08-17 01:12:59.521 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_stats:start_link() at pid <0.86.0>
2016-08-17 01:12:59.527 [info] <0.95.0>@basho_bench_valgen:init_source:88 Random source: calling crypto:rand_bytes(100663296) (override with the 'value_generator_source_size' config option
2016-08-17 01:13:01.785 [info] <0.95.0>@basho_bench_valgen:init_source:95 Random source: finished crypto:rand_bytes(100663296)
2016-08-17 01:13:01.805 [info] <0.97.0>@basho_bench_driver_redis:new:51 Using target "45.63.89.14":31037 for worker 1
2016-08-17 01:13:01.805 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_worker:start_link(basho_bench_worker_1, 1) at pid <0.95.0>
2016-08-17 01:13:01.811 [info] <0.99.0>@basho_bench_driver_redis:new:51 Using target "45.63.89.14":31037 for worker 2
2016-08-17 01:13:01.811 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_worker:start_link(basho_bench_worker_2, 2) at pid <0.98.0>
2016-08-17 01:13:01.814 [info] <0.101.0>@basho_bench_driver_redis:new:51 Using target "45.63.89.14":31037 for worker 3
2016-08-17 01:13:01.815 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_worker:start_link(basho_bench_worker_3, 3) at pid <0.100.0>
2016-08-17 01:13:01.815 [debug] <0.26.0> Supervisor kernel_safe_sup started timer:start_link() at pid <0.102.0>
2016-08-17 01:13:01.820 [info] <0.97.0>@basho_bench_worker:worker_idle_loop:237 Starting max worker: <0.97.0> on nonode@nohost
2016-08-17 01:13:01.820 [info] <0.99.0>@basho_bench_worker:worker_idle_loop:237 Starting max worker: <0.99.0> on nonode@nohost
2016-08-17 01:13:01.820 [info] <0.101.0>@basho_bench_worker:worker_idle_loop:237 Starting max worker: <0.101.0> on nonode@nohost
2016-08-17 01:13:01.820 [info] <0.7.0> Application basho_bench started on node nonode@nohost
2016-08-17 01:13:01.843 [debug] <0.106.0> Supervisor inet_gethost_native_sup started undefined at pid <0.107.0>
2016-08-17 01:13:01.844 [debug] <0.26.0> Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.106.0>
2016-08-17 01:13:09.980 [error] <0.3045.1> CRASH REPORT Process <0.3045.1> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:10.156 [error] <0.4210.1> CRASH REPORT Process <0.4210.1> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:10.829 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},2},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},2}]
2016-08-17 01:13:19.563 [error] <0.11389.2> CRASH REPORT Process <0.11389.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:19.828 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:24.363 [error] <0.31135.2> CRASH REPORT Process <0.31135.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:24.826 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:25.157 [error] <0.2191.3> CRASH REPORT Process <0.2191.3> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:25.827 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:32.378 [error] <0.31345.3> CRASH REPORT Process <0.31345.3> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:32.664 [error] <0.246.4> CRASH REPORT Process <0.246.4> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:32.826 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},2},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},2}]
2016-08-17 01:13:33.853 [error] <0.5466.4> CRASH REPORT Process <0.5466.4> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:34.421 [error] <0.7959.4> CRASH REPORT Process <0.7959.4> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:34.827 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},2},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},2}]
2016-08-17 01:13:35.507 [error] <0.13387.4> CRASH REPORT Process <0.13387.4> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:35.828 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:42.933 [error] <0.11708.5> CRASH REPORT Process <0.11708.5> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:43.826 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:45.605 [error] <0.23835.5> CRASH REPORT Process <0.23835.5> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:45.828 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:45.863 [error] <0.25292.5> CRASH REPORT Process <0.25292.5> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:46.827 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:13:49.984 [error] <0.10901.6> CRASH REPORT Process <0.10901.6> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:50.464 [error] <0.13818.6> CRASH REPORT Process <0.13818.6> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:13:50.828 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},2},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},2}]
2016-08-17 01:13:59.952 [error] <0.22559.7> CRASH REPORT Process <0.22559.7> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:14:00.828 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-17 01:14:00.832 [error] <0.26325.7> CRASH REPORT Process <0.26325.7> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:14:00.931 [error] <0.26924.7> CRASH REPORT Process <0.26924.7> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-17 01:14:01.827 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},2},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},2}]
2016-08-17 01:14:02.836 [info] <0.86.0>@basho_bench_stats:report_total_errors:294 Total Errors:
2016-08-17 01:14:02.836 [info] <0.86.0>@basho_bench_stats:report_total_errors:300   {{get,get},{connection_error,{connection_error,eaddrnotavail}}}: 18
2016-08-17 01:14:02.836 [info] <0.86.0>@basho_bench_stats_writer_csv:terminate:62 module=basho_bench_stats_writer_csv event=stop stats_sink=csv
2016-08-17 01:14:02.841 [info] <0.7.0> Application basho_bench exited with reason: stopped
